## Useful methods : 
1. specify the type : np.array([1 , 2.1 ] dtype={type})
2. make multi d from noraml array when the elements of the array treated as rows : OPArr = np.array(range(i , i+3) for i  in L)
3. reshaping : shape() : return a tuple the the dimension of the darray , reshape(row , colum) reshape it to the specified dimensions 
4. shape : is tuple of the legnth of dimension (ndim) , the contain the length of array in every dimmension
5. ndim the number of axes (pdemension )

In [5]:
import numpy as np
ZerosArr = np.zeros(300 , dtype=int)
L = [1 , 2 , 3]
# OPArr = np.array(range(i , i+3) for i  in L)
# print(OPArr)
Reshaped = ZerosArr.reshape(3 ,25, 2 , 2)
print(Reshaped)
print("SHAAPED :" , Reshaped.shape , ZerosArr.shape , Reshaped.ndim)

[[[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]