In [ ]:
import numpy as np
np.random.seed(888)
# 1D random array
# with mean is the peak or center  and standard deviation to 1
rng = np.random.normal(loc=0 , scale = 1 ,size =(100)).astype(np.int16)
Drng = np.random.uniform(low=1 , high=10 , size= (8,8)).astype(np.int16)
Trng = np.random.uniform(low=1 , high=17 , size=(4,2,5)).astype(np.int16)
print(Trng)



[[[ 2 12 12 16 10]
  [ 4  9 10 10  7]]

 [[13 10  3 16 16]
  [12 14 15  6  1]]

 [[12 16  4  5 10]
  [ 4  2  3  4 12]]

 [[12  4  7  7  5]
  [10  2 15  2 12]]]
