In [23]:
import numpy as np 
Vector = np.ones(shape=(9,9) ,dtype=np.int16)
# print(Vector  )
Vector[1:8, 1:8] = 0
Vector[2:7, 2:7] = 1
Vector[3:6, 3:6] = 0
Vector[4:5, 4] = 1
array_1 = np.array([1,2,3,4,5], dtype=np.int8)
array_2 = np.array([1,2,3], dtype=np.int8)
OutputArr = array_2  * array_1[:,np.newaxis] 
print(Vector)
print(OutputArr)

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]
[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]
